import java.util.Objects;
// I used ChatGPT to help me with this code because I was running into problems
// and ChatGPT helped me debug it!

public class LineSegment {
    //Fields
    private Point2D startPoint;
    private Point2D endPoint;

    // Default constructor
    public LineSegment() {
        this.startPoint = new Point2D(0,0);
        this.endPoint = new Point2D(0,0);
    }

    // Constructor with Point2D parameters
    public LineSegment(Point2D startPoint, Point2D endPoint) {
        this.setStart(startPoint != null ? new Point2D(startPoint) : new Point2D(0, 0));
        this.setEnd(endPoint != null ? new Point2D(endPoint) : new Point2D(0, 0));
    }

    //Copy constructor
    public LineSegment(LineSegment anotherLineSegment) {
        this.startPoint = new Point2D(anotherLineSegment.startPoint);
        this.endPoint = new Point2D(anotherLineSegment.endPoint);
    }

    // Getters and setters
    public Point2D getStart() {
        return new Point2D(startPoint);
    }

    public void setStart(Point2D startPoint) {
        this.startPoint = new Point2D(startPoint);
    }

    public Point2D getEnd() {
        return new Point2D(endPoint);
    }
    public void setEnd(Point2D endPoint) {
        this.endPoint = new Point2D(endPoint);
    }

    public String toString() {
        return "LineSegment{" +
                "startPoint=" + startPoint +
                ", endPoint=" + endPoint +
                '}';
    }
    public double getDistance() {
        return Math.sqrt(Math.pow(endPoint.getX() - startPoint.getX(), 2) + Math.pow(endPoint.getY() - startPoint.getY(), 2));
    }

    @Override // Generated by IntellIJ
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        LineSegment that = (LineSegment) o;
        return Objects.equals(startPoint, that.startPoint) && Objects.equals(endPoint, that.endPoint);
    }

    // Getters that protect against privacy leaks
    public Point2D getStartPoint() {
        return new Point2D(startPoint);
    }
    public Point2D getEndPoint() {
        return new Point2D(endPoint);
    }
}
/* Questions:
1. What is a privacy leak?
When a method returns an instance variable with a reference type
2. Do your getters or setters have privacy leaks?
I think so but we fixed it!
3. Where else could a privacy leak occur?
 */
